services:
  - type: web
    name: event-ticketing
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: DB_HOST
        fromDatabase:
          name: event_ticketing
          property: host
      - key: DB_NAME
        fromDatabase:
          name: event_ticketing
          property: database
      - key: DB_USER
        fromDatabase:
          name: event_ticketing
          property: user
      - key: DB_PASS
        fromDatabase:
          name: event_ticketing
          property: password

databases:
  - name: event_ticketing
    plan: free
